name: signin
# on: [push]
on:
  workflow_dispatch:
  schedule:
    - cron:  '45 0,9 * * 1-5'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'
      - run: pip install requests
      - run: python src/WxWorkMsg.py
env: 
    WEBHOOK: ${{ secrets.YJWEBHOOK }}
    CONTENT: "打卡"
    MOBILE: ""
